name: Mechanics
version: '${version}'
main: dev.wuason.mechanics.Mechanics
api-version: 1.18
load: STARTUP
authors: [ Wuason ]
description: Add mechanics to your server!
website: techmc.es
softdepend:
  - PlaceholderAPI
  - ItemsAdder
  - Oraxen
  - MythicMobs
  - MMOItems
  - CustomItems
  - ExecutableBlocks
  - ExecutableItems
  - Towny
  - WorldGuard
  - Factions
  - Lands
  - PlotSquared
  - CrashClaim